# This file should be at the root of your Git repository (e.g., proliga-front/codemagic.yaml)
workflows:
  pwabuilder-ios:
    name: Build PWABuilder iOS app
    environment:
      xcode: latest # or '16.4'
      # CodeMagic automatically sets these if you upload signing files in the UI.
      # You can find their names in the "Code signing" section after uploading.
      # Example:
      # CM_PROVISIONING_PROFILE_NAME: "$CM_PROVISIONING_PROFILE_NAME_FOR_PROLIGA_APP_STORE"
      # CM_CERTIFICATE_UUID: "$CM_CERTIFICATE_UUID_FOR_PROLIGA_APP_STORE"
      # (Actual variable names might vary based on your CodeMagic setup and how you name them)

    scripts:
      - name: Install CocoaPods
        script: |
          gem install cocoapods

      - name: Install Pods
        script: |
          echo "Installing Pods..."
          cd ios
          pod install
          cd ..

      - name: Archive iOS app with xcodebuild
        script: |
          echo "Archiving iOS app..."
          # Pass signing variables that CodeMagic provides via environment
          # Make sure these are properly configured in CodeMagic's UI for "Code signing"
          xcodebuild -workspace ios/Proliga.uz.xcworkspace \
                     -scheme Proliga.uz \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/Proliga.uz.xcarchive \
                     archive \
                     PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE" \ # CodeMagic's variable
                     DEVELOPMENT_TEAM="$CM_TEAM_ID" # CodeMagic's variable (you need to define CM_TEAM_ID in env variables)
                     # Or directly provide the ID if not using CM_TEAM_ID env var:
                     # DEVELOPMENT_TEAM="YOUR_ACTUAL_TEAM_ID"

      - name: Export IPA
        script: |
          echo "Exporting IPA..."
          # The -archivePath here MUST match the path from the 'archive' command.
          # CM_BUILD_DIR is the correct way to refer to CodeMagic's designated build output directory.
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/Proliga.uz.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/export
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa