workflows:
  pwabuilder-ios:
    name: Build PWABuilder iOS app
    environment:
      xcode: latest
    scripts:
      - name: Install any dependencies (optional)
        script: |
          echo "PWABuilder apps usually don't need npm installs"
      - name: Build iOS app with xcodebuild
        script: |
          # First xcodebuild command (ARCHIVE) - all on one line
          xcodebuild -workspace ios/Proliga.uz.xcworkspace -scheme Proliga.uz -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/Proliga.uz.xcarchive archive

          # Second xcodebuild command (EXPORT) - all on one line
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Proliga.uz.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $CM_BUILD_DIR/export
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa