# This file should be at the root of your Git repository (e.g., proliga-front/codemagic.yaml)
workflows:
  pwabuilder-ios:
    name: Build PWABuilder iOS app
    environment:
      xcode: latest # or '16.4'
      # It's good practice to set these in CodeMagic's UI as secure environment variables.
      # For example, under "Environment variables" in CodeMagic:
      # CM_TEAM_ID: YOUR_ACTUAL_TEAM_ID (e.g., ABCDE12345) - Mark as secure
      # CM_PROVISIONING_PROFILE: "Your Provisioning Profile Name" - Mark as secure if it contains sensitive info
      # Or you might let CodeMagic auto-inject if you only use the "Code signing" UI.

    scripts:
      - name: Install CocoaPods
        script: |
          gem install cocoapods

      - name: Install Pods
        script: |
          echo "Installing Pods..."
          cd ios
          pod install
          cd ..

      - name: Archive iOS app with xcodebuild
        script: |
          echo "Archiving iOS app..."
          xcodebuild -workspace ios/Proliga.uz.xcworkspace \
                     -scheme Proliga.uz \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/Proliga.uz.xcarchive \
                     archive \
                     PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE" \
                     DEVELOPMENT_TEAM="$CM_TEAM_ID" # <--- REMOVED COMMENT ON THIS LINE
                     # You can add comments on separate lines like this for clarity:
                     # Make sure CM_PROVISIONING_PROFILE and CM_TEAM_ID are defined in CodeMagic environment variables.
                     # Or replace with hardcoded values if you're not using CM env vars.

      - name: Export IPA
        script: |
          echo "Exporting IPA..."
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/Proliga.uz.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/export
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa