
name: Build, Push, and Scan Docker Image with Anchore

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4


        
      - name: Generate .env.production from base64 GitHub Secret
        run: |
          echo "${{ secrets.PRODUCTION_BASE64 }}" | base64 -d > .env.production
          if [ -s .env.production ]; then
            echo "✅ .env.production created from base64"
          else
            echo "❌ Failed to create .env.production"
            exit 1
          fi

      # Set up QEMU for multi-platform builds (optional, remove if not needed)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/js-docker-k:0.0.1
          platforms: linux/amd64,linux/arm64  # Optional: specify platforms for multi-arch builds

      # Scan the Docker image with Anchore Grype
      - name: Scan image with Anchore
        uses: anchore/scan-action@v6
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/js-docker-k:0.0.1
          fail-build: true
          severity-cutoff: critical
          output-format: sarif