name: Build and Deploy (Self-Hosted Ubuntu)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build & Restart App
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Generate .env.production from GitHub Secrets
        run: |
          echo "PORT=3000" > .env.production

          echo "# APP SETTINGS" >> .env.production
          echo "NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}" >> .env.production
          echo "NEXT_PUBLIC_STATIC_URL=${{ secrets.NEXT_PUBLIC_STATIC_URL }}" >> .env.production
          echo "NEXT_PUBLIC_MAXMIND_DB_PATH=${{ secrets.NEXT_PUBLIC_MAXMIND_DB_PATH }}" >> .env.production
          echo "NEXT_PUBLIC_BANNER_ONE_RENDER_WIDTH=${{ secrets.NEXT_PUBLIC_BANNER_ONE_RENDER_WIDTH }}" >> .env.production
          echo "NEXT_PUBLIC_BANNER_TWO_RENDER_WIDTH=${{ secrets.NEXT_PUBLIC_BANNER_TWO_RENDER_WIDTH }}" >> .env.production

          echo "" >> .env.production
          echo "# AUTH" >> .env.production
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env.production
          echo "AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }}" >> .env.production
          echo "AUTH_URL=${{ secrets.AUTH_URL }}" >> .env.production
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
          echo "YANDEX_CLIENT_ID=${{ secrets.YANDEX_CLIENT_ID }}" >> .env.production
          echo "YANDEX_CLIENT_SECRET=${{ secrets.YANDEX_CLIENT_SECRET }}" >> .env.production

          echo "" >> .env.production
          echo "# DATABASE" >> .env.production
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.production
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.production
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.production

          echo "" >> .env.production
          echo "# PAYMENT" >> .env.production
          echo "NEXT_PUBLIC_CLICK_SERVICE_ID=${{ secrets.NEXT_PUBLIC_CLICK_SERVICE_ID }}" >> .env.production
          echo "NEXT_PUBLIC_CLICK_EXPENSE_SERVICE_ID=${{ secrets.NEXT_PUBLIC_CLICK_EXPENSE_SERVICE_ID }}" >> .env.production
          echo "NEXT_PUBLIC_CLICK_MERCHANT_ID=${{ secrets.NEXT_PUBLIC_CLICK_MERCHANT_ID }}" >> .env.production
          echo "NEXT_PUBLIC_PAYME_ID=${{ secrets.NEXT_PUBLIC_PAYME_ID }}" >> .env.production
          echo "NEXT_PUBLIC_PAYME_EXPENSE_ID=${{ secrets.NEXT_PUBLIC_PAYME_EXPENSE_ID }}" >> .env.production

          echo "" >> .env.production
          echo "# SITE CONFIG" >> .env.production
          echo "NEXT_PUBLIC_ALLOWED_DOMAINS=${{ secrets.NEXT_PUBLIC_ALLOWED_DOMAINS }}" >> .env.production

          echo "" >> .env.production
          echo "# FIREBASE" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_VAPID_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY }}" >> .env.production
          echo "FIREBASE_ADMIN_CREDENTIALS='${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}'" >> .env.production

          echo "" >> .env.production
          echo "# ANALYTICS" >> .env.production
          echo "NEXT_PUBLIC_YANDEX_METRIKA_ID=${{ secrets.NEXT_PUBLIC_YANDEX_METRIKA_ID }}" >> .env.production

          echo "✅ .env.production generated successfully"

      - name: Generate Prisma client
        run: pnpm exec prisma generate

      - name: Build application
        run: pnpm run build

      - name: Restart application with PM2
        run: |
          pm2 start pnpm --name proliga -- start