name: Build and Deploy (Self-Hosted Ubuntu)

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build App
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
          run_install: false

      # - name: Generate .env.production from GitHub Secrets
      #   run: |
      #     echo "${{ secrets.PRODUCTION }}" > .env.production
      #     echo "✅ .env.production generated successfully"
      #     cat .env.production
      - name: Generate .env.production from GitHub Secrets
        # CRITICAL: Use PowerShell's Out-File to write the secret content.
        # This will correctly handle newlines and special characters within the secret.
        # -Encoding utf8NoBOM is crucial for .env files in Node.js environments on Windows.
        run: |
          "${{ secrets.PRODUCTION }}" | Out-File -FilePath ".env.production" -Encoding utf8NoBOM
          Write-Host "✅ .env.production generated successfully"
          # Optional: Verify content. REMOVE FOR PRODUCTION!
          Write-Host "--- Content of .env.production (first few lines) ---"
          Get-Content -Head 5 .env.production
          Write-Host "----------------------------------------------------"
        shell: pwsh
      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: pnpm exec prisma generate

      - name: Build application
        run: pnpm run build

      - name: Restart application with PM2
        run: pm2 start pnpm --name proliga -- start
