name: Build and Deploy (Self-Hosted Ubuntu)

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build App
    runs-on: [self-hosted, linux]
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
      - name: Check formating
        run: pnpm lint -- --max-warnings=0

      - name: Check Styling
        run: pnpm format:check
