name: Scan Docker Hub Image

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Generate metadata for the image
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/komoliddin/proliga-front
          tags: |
            type=raw,value=main

      # Run Docker Scout with CVE checks, recommendations, and comparison
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          organization: komoliddin
          command: cves,recommendations,compare
          image: ${{ steps.meta.outputs.tags }}
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
          github-token: ${{ secrets.TOKEN }}
