name: Scan Docker Hub Image

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (optional, if you need to access any files)
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (optional, ensures Docker is ready)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub (if the image is private)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Scan the Docker Hub image
      - name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name == 'push' }}
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ steps.meta.outputs.tags }}
          to: "docker.io/komoliddin/proliga-front:main"
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.TOKEN }} # to be able to write the comment